//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
namespace OrdenesServicio_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesServicio
    {
        //public partial class OrdenesServicio : DbContext
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesServicio()
        {
            this.Equipos = new HashSet<Equipos>();
        }
    
        public int Folio { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Usuario { get; set; }
        public string Empresa { get; set; }
        public string TelCel { get; set; }
        public string Area { get; set; }
        public string Sucursal { get; set; }
        public string Email { get; set; }
        public string Requerimiento { get; set; }
        public string Acciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipos> Equipos { get; set; }
    }
}
